### ISSUE TITLE
New build issue

### ISSUE THREAD

**Issue by DuckyThePilot** [jbzdarkid/witness-trainer#11]
On game launch, I am receiving this with the new release. Old still works.

---------------------------
WitnessTrainer encountered an error.
---------------------------
WitnessTrainer version 1.8.3 has encountered an error.
Please press Control C to copy this error, and paste it to darkid.
0x4f8ef 0x4f8ef 0x4fad2 0x51096 0x18dd1 0x506af 0x50976 0x19bab 0x2c8d8 0x3b96154e0 0x3bacc485b 
---------------------------
OK   
---------------------------

**Comment by jbzdarkid** [comment]
Fixed in 1.8.4 -- thank you for the quick report!
