### ISSUE TITLE
Request: Support for Issued_Sound details with ExportEntities

### ISSUE THREAD

**Issue by cmathew** [jbzdarkid/witness-trainer#5]
The sound engine for this game is pretty subtle; it would be neat to see exactly which assets make up the ambience at any given time. 

Currently it seems that ExportEntities is hardcoded to look for Power_Cables only.

**Comment by jbzdarkid** [comment]
ExportEntities is something that only exists in debug, I regularly change it and recompile. If you want to export another entity type, change the values in your own copy.
