### ISSUE TITLE
Developer menu and console

### ISSUE THREAD

**Issue by cruuud** [jbzdarkid/witness-trainer#7]
Could you incorporate the Developer console in the Witness game menu, where you can teleport to certain locations and instantaneously solve a panel?
Oh and maybe also the in-game console where you can enter commands like ls, quit etcetera?

**Comment by jbzdarkid** [comment]
The ingame console is available, but I'm not sure exactly what the developer menu is. Can you post a screenshot of it?

Some functionality is not available in the released copy of the game, as it is compiled out.

**Comment by cruuud** [comment]
> The ingame console is available, but I'm not sure exactly what the developer menu is. Can you post a screenshot of it?
> 
> 
> 
> Some functionality is not available in the released copy of the game, as it is compiled out.

The developer menu is the menu you can see if you press Escape, you would see a menu item named Developer. Via that menu you then have other menu options to teleport to a given location, or instantaneously solve a panel.
How did you enable the console?
I think I have interesting information for you which I will only share with you as you have also put alot of time in this. Email me at 0rchard@protonmail.com if you are interested.

**Comment by jbzdarkid** [comment]
I got this working (for me, it's not committed) by swapping the settings and developer menus.
However, it doesn't seem like there's that much of 
use in said menu -- so I am not including it in the trainer.
![image](https://user-images.githubusercontent.com/5459085/143770653-18cb22b8-00df-4226-99f8-5eb439666f5b.png)

**Comment by cruuud** [comment]
> I got this working (for me, it's not committed) by swapping the settings and developer menus.
> 
> However, it doesn't seem like there's that much of 
> 
> use in said menu -- so I am not including it in the trainer.
> 
> ![image](https://user-images.githubusercontent.com/5459085/143770653-18cb22b8-00df-4226-99f8-5eb439666f5b.png)
> 
> 

Ok, guess you have not found the importance of it and how to access the suns secret. Maybe you will find it.

**Comment by jbzdarkid** [comment]
I don't know why you're being cautious about spoilers in a program that is for speedrunners about cheating the game.
If you're talking about environmenal puzzles, I don't see how this menu helps.
If you're talking about the second ending (from the sun EP), I don't see how this menu helps.
I don't know what else you could be talking about.

**Comment by cruuud** [comment]
Scattered around the island are clues for a secret to be found and afaik, no one has found this yet. It has to do with the sun markings you can find on some entities.
Now that is all I am going to say about this, it has taken me alot of time and luck to figure it all out and the enjoyment is greater if you find it out for yourself.
